[package]
name = "snarkvm"
version = "4.6.0"
authors = [ "The Aleo Team <hello@aleo.org>" ]
description = "A decentralized virtual machine"
homepage = "https://aleo.org"
repository = "https://github.com/ProvableHQ/snarkVM"
keywords = [
  "aleo",
  "cryptography",
  "blockchain",
  "decentralized",
  "zero-knowledge"
]
categories = [
  "compilers",
  "cryptography",
  "mathematics",
  "wasm",
  "web-programming"
]
include = [ "Cargo.toml", "vm", "README.md", "LICENSE.md" ]
license = "Apache-2.0"
edition = "2024"
rust-version = "1.88.0" # Attention - Change the MSRV in rust-toolchain and in .circleci/config.yml as well

[lib]
path = "vm/lib.rs"

[features]
default = [
  "algorithms",
  "circuit",
  "console",
  "ledger",
  "parameters",
  "synthesizer",
  "utilities",
  "package",
  "file",
]
full = [
  "default",
  "curves",
  "fields",
]
file = [
  "console",
  "synthesizer",
  "dep:serde_json"
]
package = [
  "algorithms",
  "circuit",
  "file",
  "ledger",
  "snarkvm-console/filesystem",
  "dep:ureq",
  "dep:dotenvy"
]

async = [ "snarkvm-ledger/async", "snarkvm-synthesizer/async" ]
cuda = [ "snarkvm-algorithms/cuda" ]
history = [ "snarkvm-synthesizer/history" ]
history-staking-rewards = [ "snarkvm-synthesizer/history-staking-rewards" ]
slipstream-plugins = [ "snarkvm-synthesizer/slipstream-plugins" ]
parameters_no_std_out = [ "snarkvm-parameters/no_std_out" ]
locktick = [
  "snarkvm-console?/locktick",
  "snarkvm-algorithms?/locktick",
  "snarkvm-ledger?/locktick",
  "snarkvm-parameters?/locktick",
  "snarkvm-synthesizer?/locktick"
]
noconfig = [ ]
prop-tests = [ "snarkvm-ledger?/prop-tests" ]
rocks = [ "snarkvm-ledger/rocks", "snarkvm-synthesizer/rocks" ]
test = [ "snarkvm-ledger/test" ]
test-helpers = [ "snarkvm-ledger/test-helpers" ]
timer = [ "snarkvm-ledger/timer" ]
algorithms = [ "snarkvm-algorithms" ]
circuit = [ "snarkvm-circuit" ]
console = [ "snarkvm-console" ]
curves = [ "snarkvm-curves" ]
fields = [ "snarkvm-fields" ]
ledger = [ "snarkvm-ledger" ]
metrics = [ "snarkvm-metrics", "snarkvm-ledger/metrics" ]
parameters = [ "snarkvm-parameters" ]
synthesizer = [ "snarkvm-synthesizer" ]
utilities = [ "snarkvm-utilities" ]
wasm = [ "snarkvm-wasm" ]
serial = [
  "snarkvm-algorithms?/serial",
  "snarkvm-console?/serial",
  "snarkvm-curves?/serial",
  "snarkvm-fields?/serial",
  "snarkvm-utilities/serial",
  "snarkvm-ledger?/serial"
]
snark-print = [ "snarkvm-algorithms?/snark-print" ]

dev-print = [ 
  "snarkvm-utilities/dev-print",
  "snarkvm-algorithms/dev-print",
  "snarkvm-circuit/dev-print",
  "snarkvm-curves/dev-print",
  "snarkvm-fields/dev-print",
  "snarkvm-parameters/dev-print",
  "snarkvm-synthesizer/dev-print",
]
dev_skip_checks = [
  "snarkvm-console/dev_skip_checks",
  "snarkvm-synthesizer/dev_skip_checks"
]
save_r1cs_hashes = [ "snarkvm-circuit/save_r1cs_hashes" ]
test_exports = [ "snarkvm-algorithms/test_exports" ]
test_targets = [ "snarkvm-console/test_targets" ]
test_consensus_heights = [ "snarkvm-console/test_consensus_heights", "snarkvm-synthesizer/test_consensus_heights" ]

[dependencies.snarkvm-algorithms]
workspace = true
optional = true

[dependencies.snarkvm-circuit]
workspace = true
optional = true

[dependencies.snarkvm-console]
workspace = true
optional = true
features = [ "default" ]

[dependencies.snarkvm-curves]
workspace = true
optional = true

[dependencies.snarkvm-fields]
workspace = true
optional = true

[dependencies.snarkvm-ledger]
workspace = true
optional = true

[dependencies.snarkvm-metrics]
workspace = true
optional = true

[dependencies.snarkvm-parameters]
workspace = true
optional = true

[dependencies.snarkvm-synthesizer]
workspace = true
optional = true

[dependencies.snarkvm-utilities]
workspace = true
optional = true

[dependencies.snarkvm-wasm]
workspace = true
optional = true

[dependencies.anyhow]
workspace = true

[dependencies.dotenvy]
version = "0.15"
optional = true

[dependencies.rand]
workspace = true

[dependencies.serde_json]
workspace = true
optional = true
features = [ "preserve_order" ]

[dependencies.ureq]
workspace = true
optional = true
features = [ "json" ]
default-features = true

[dev-dependencies.snarkvm]
path = "."

[dev-dependencies.bincode]
workspace = true

[dev-dependencies.rusty-hook]
version = "0.11.2"

[dev-dependencies.tempfile]
workspace = true

[build-dependencies.walkdir]
version = "2"

[profile.release]
opt-level = 3
lto = "thin"
incremental = true

[profile.bench]
opt-level = 3
debug = false
rpath = false
lto = "thin"
incremental = true
debug-assertions = false

[profile.dev]
opt-level = 3
lto = "off"
incremental = true

[profile.test]
opt-level = 3
lto = "thin"
incremental = true
debug = true
debug-assertions = true

